a=int(input("Emter any number:- "))
b=int(input("Emter another number:- "))
print("sum of number :- ",a+b)
print("Multiplication of two number:- ",a*b)
print("Division of two number:- ",a/b)
print("Addition of two number:- ",a+b)
print("Subtraction of two number:- ",a-b)
print("Power of number:- ",a**b)